version: '2'
# Author: ghifari
services:
  webserver:
    image: nginx:latest
    container_name: nginx_compose1
    volumes:
    - web-data:/usr/share/nginx/html
    ports:
    - '8080:80'
    networks:
    - latihan-compose1

  mysql:
    image: mysql:5.7
    container_name: mysql_compose1
    environment: 
    - MYSQL_ROOT_PASSWORD=admin123
    networks: 
    - latihan-compose1

  phpmyadmin:
    image: phpmyadmin-custom:latest
    links: 
    - "mysql:db"
    ports: 
    - '9000:80'
    networks: 
    - latihan-compose1

volumes:
  web-data:

networks:
  latihan-compose1: